apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.annotations.CUSTOM_PROJECT_NAME }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9443
